//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_status_facture
    {
        public ref_status_facture()
        {
            this.t_ref_facturation_historique = new HashSet<t_ref_facturation_historique>();
        }
    
        public int id_facture { get; set; }
        public string fact_nom { get; set; }
    
        public virtual ICollection<t_ref_facturation_historique> t_ref_facturation_historique { get; set; }
    }
}
