//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_adresse
    {
        public t_adresse()
        {
            this.ref_user_adress = new HashSet<ref_user_adress>();
        }
    
        public int id_adresse { get; set; }
        public int id_ville { get; set; }
        public string adr_libelle { get; set; }
        public System.DateTime adr_date_modification { get; set; }
    
        public virtual ICollection<ref_user_adress> ref_user_adress { get; set; }
        public virtual t_villes t_villes { get; set; }
    }
}
