//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_category_competence
    {
        public t_category_competence()
        {
            this.t_competence = new HashSet<t_competence>();
        }
    
        public int id_category_comp { get; set; }
        public string category_comp_nom { get; set; }
    
        public virtual ICollection<t_competence> t_competence { get; set; }
    }
}
