//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_regions
    {
        public t_regions()
        {
            this.t_departement = new HashSet<t_departement>();
        }
    
        public int id_region { get; set; }
        public int id_pays { get; set; }
        public string region_nom { get; set; }
    
        public virtual ICollection<t_departement> t_departement { get; set; }
        public virtual t_pays t_pays { get; set; }
    }
}
