//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_villes
    {
        public t_villes()
        {
            this.t_adresse = new HashSet<t_adresse>();
        }
    
        public int id_villes { get; set; }
        public Nullable<int> id_departement { get; set; }
        public string ville_slug { get; set; }
        public string ville_nom { get; set; }
        public string ville_nom_simple { get; set; }
        public string ville_nom_reel { get; set; }
        public string ville_nom_soundex { get; set; }
        public string ville_nom_metaphone { get; set; }
        public string ville_code_postal { get; set; }
        public string ville_commune { get; set; }
        public string ville_code_commune { get; set; }
        public Nullable<short> ville_arrondissement { get; set; }
        public string ville_canton { get; set; }
        public Nullable<short> ville_amdi { get; set; }
        public Nullable<decimal> ville_longitude_deg { get; set; }
        public Nullable<decimal> ville_latitude_deg { get; set; }
    
        public virtual ICollection<t_adresse> t_adresse { get; set; }
        public virtual t_departement t_departement { get; set; }
    }
}
