//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuctionJobEntities : DbContext
    {
        public AuctionJobEntities()
            : base("name=AuctionJobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ref_banque> ref_banque { get; set; }
        public virtual DbSet<ref_competence_user> ref_competence_user { get; set; }
        public virtual DbSet<ref_status_facture> ref_status_facture { get; set; }
        public virtual DbSet<ref_type_carte_bancaire> ref_type_carte_bancaire { get; set; }
        public virtual DbSet<ref_user_adress> ref_user_adress { get; set; }
        public virtual DbSet<t_adresse> t_adresse { get; set; }
        public virtual DbSet<t_annonce> t_annonce { get; set; }
        public virtual DbSet<t_annonce_proposition> t_annonce_proposition { get; set; }
        public virtual DbSet<t_carte_bancaire> t_carte_bancaire { get; set; }
        public virtual DbSet<t_category_competence> t_category_competence { get; set; }
        public virtual DbSet<t_competence> t_competence { get; set; }
        public virtual DbSet<t_departement> t_departement { get; set; }
        public virtual DbSet<t_group> t_group { get; set; }
        public virtual DbSet<t_level> t_level { get; set; }
        public virtual DbSet<t_member_group> t_member_group { get; set; }
        public virtual DbSet<t_pays> t_pays { get; set; }
        public virtual DbSet<t_pins> t_pins { get; set; }
        public virtual DbSet<t_recompense> t_recompense { get; set; }
        public virtual DbSet<t_recompense_user> t_recompense_user { get; set; }
        public virtual DbSet<t_ref_facturation_historique> t_ref_facturation_historique { get; set; }
        public virtual DbSet<t_regions> t_regions { get; set; }
        public virtual DbSet<t_statut_annonce> t_statut_annonce { get; set; }
        public virtual DbSet<t_type_user> t_type_user { get; set; }
        public virtual DbSet<t_user> t_user { get; set; }
        public virtual DbSet<t_user_info> t_user_info { get; set; }
        public virtual DbSet<t_villes> t_villes { get; set; }
        public virtual DbSet<ref_competence_annonce> ref_competence_annonce { get; set; }
        public virtual DbSet<ref_competence_group> ref_competence_group { get; set; }
    }
}
