//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_competence_annonce
    {
        public Nullable<int> id_annonce { get; set; }
        public int id_competence { get; set; }
        public int lvl_wait { get; set; }
        public short isactually { get; set; }
    
        public virtual t_annonce t_annonce { get; set; }
        public virtual t_competence t_competence { get; set; }
    }
}
