//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_competence_user
    {
        public int id_user { get; set; }
        public int id_competence { get; set; }
        public int lvl_competence { get; set; }
        public short isactually { get; set; }
    
        public virtual t_competence t_competence { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
