//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_annonce
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_annonce()
        {
            this.ref_competence_annonce = new HashSet<ref_competence_annonce>();
        }
    
        public int id_annonce { get; set; }
        public int fk_id_useradmin { get; set; }
        public Nullable<int> fk_id_user_win { get; set; }
        public Nullable<int> fk_id_statutannonce { get; set; }
        public Nullable<double> fk_id_category { get; set; }
        public double fk_id_adresse { get; set; }
        public string annonce_title { get; set; }
        public string annonce_subtittle { get; set; }
        public string annonce_description_mission { get; set; }
        public double annonce_prix { get; set; }
        public short annonce_validate { get; set; }
        public System.DateTime annonce_start { get; set; }
        public Nullable<System.DateTime> annonce_deadline { get; set; }
        public System.DateTime annonce_modification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ref_competence_annonce> ref_competence_annonce { get; set; }
        public virtual t_user t_user { get; set; }
        public virtual t_user t_user1 { get; set; }
        public virtual t_statut_annonce t_statut_annonce { get; set; }
        public virtual t_annonce_proposition t_annonce_proposition { get; set; }
    }
}
