//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_annonce_proposition
    {
        public int id_anno_proposition { get; set; }
        public int fk_id_user { get; set; }
        public int fk_id_annonce { get; set; }
        public string annopro_description { get; set; }
        public double annopro_prix { get; set; }
        public System.DateTime annopro_create { get; set; }
    
        public virtual t_annonce t_annonce { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
