//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_carte_bancaire
    {
        public int id_carte_bancaire { get; set; }
        public int fk_id_typecarte { get; set; }
        public int fk_id_utilisateur { get; set; }
        public int fk_id_banque { get; set; }
        public System.DateTime cb_date_expiration { get; set; }
        public string cb_nom { get; set; }
        public string cb_prenom { get; set; }
        public Nullable<decimal> cb_prix_facturation { get; set; }
        public short cb_crypto { get; set; }
    
        public virtual ref_banque ref_banque { get; set; }
        public virtual ref_type_carte_bancaire ref_type_carte_bancaire { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
