//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_departement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_departement()
        {
            this.t_villes = new HashSet<t_villes>();
        }
    
        public int id_departement { get; set; }
        public Nullable<int> id_region { get; set; }
        public string departement_code { get; set; }
        public string departement_nom { get; set; }
        public string departement_nom_uppercase { get; set; }
        public string departement_slug { get; set; }
        public string departement_nom_soundex { get; set; }
    
        public virtual t_regions t_regions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_villes> t_villes { get; set; }
    }
}
