//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_member_group
    {
        public int id_member { get; set; }
        public int fk_id_user { get; set; }
        public int fk_id_group { get; set; }
        public short member_group_isenable { get; set; }
        public System.DateTime member_group_date { get; set; }
    
        public virtual t_group t_group { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
