//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_member_group
    {
        public int id_member { get; set; }
        public int fk_id_user { get; set; }
        public int fk_id_group { get; set; }
        public short member_group_isenable { get; set; }
        public System.DateTime member_group_date { get; set; }
    
        public virtual t_group t_group { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
