//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_pays
    {
        public t_pays()
        {
            this.t_regions = new HashSet<t_regions>();
        }
    
        public int id_pays { get; set; }
        public Nullable<short> pays_code { get; set; }
        public string pays_alpha2 { get; set; }
        public string pays_alpha3 { get; set; }
        public string pays_nom_fr_fr { get; set; }
        public string pays_nom_en_gb { get; set; }
    
        public virtual ICollection<t_regions> t_regions { get; set; }
    }
}
