//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_recompense_user
    {
        public int id_recompense_user { get; set; }
        public int fk_id_user { get; set; }
        public Nullable<int> fk_id_recompense { get; set; }
        public System.DateTime date_obtention { get; set; }
    
        public virtual t_recompense t_recompense { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
