//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_recompense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_recompense()
        {
            this.t_recompense_user = new HashSet<t_recompense_user>();
        }
    
        public int id_recompense { get; set; }
        public string recompense_nom { get; set; }
        public string recompense_description { get; set; }
        public double recompense_credit { get; set; }
        public double recompense_xp { get; set; }
        public int recompense_type_user { get; set; }
    
        public virtual t_type_user t_type_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_recompense_user> t_recompense_user { get; set; }
    }
}
