//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ref_facturation_historique
    {
        public t_ref_facturation_historique()
        {
            this.t_user = new HashSet<t_user>();
        }
    
        public int id_facturation { get; set; }
        public Nullable<int> fk_id_statut_facturation { get; set; }
        public System.DateTime date_modification { get; set; }
    
        public virtual ref_status_facture ref_status_facture { get; set; }
        public virtual ICollection<t_user> t_user { get; set; }
    }
}
