//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_type_user
    {
        public t_type_user()
        {
            this.t_recompense = new HashSet<t_recompense>();
            this.t_user_info = new HashSet<t_user_info>();
        }
    
        public int id_typeuser { get; set; }
        public string typeuser_nom { get; set; }
    
        public virtual ICollection<t_recompense> t_recompense { get; set; }
        public virtual ICollection<t_user_info> t_user_info { get; set; }
    }
}
