//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_villes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_villes()
        {
            this.t_adresse = new HashSet<t_adresse>();
        }
    
        public int id_villes { get; set; }
        public Nullable<int> id_departement { get; set; }
        public string ville_slug { get; set; }
        public string ville_nom { get; set; }
        public string ville_nom_simple { get; set; }
        public string ville_nom_reel { get; set; }
        public string ville_nom_soundex { get; set; }
        public string ville_nom_metaphone { get; set; }
        public string ville_code_postal { get; set; }
        public string ville_commune { get; set; }
        public string ville_code_commune { get; set; }
        public Nullable<short> ville_arrondissement { get; set; }
        public string ville_canton { get; set; }
        public Nullable<short> ville_amdi { get; set; }
        public Nullable<decimal> ville_longitude_deg { get; set; }
        public Nullable<decimal> ville_latitude_deg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_adresse> t_adresse { get; set; }
        public virtual t_departement t_departement { get; set; }
    }
}
