//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtoRefTypeCarteBancaire
    {
        public int id_type { get; set; }
        public string tcb_nom { get; set; }
    
        public virtual ICollection<DtoTCarteBancaire> t_carte_bancaire { get; set; }
    }
}
