//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;

    public partial class DtoRefCompetenceAnnonce
    {
        public Nullable<int> id_annonce { get; set; }
        public int id_competence { get; set; }
        public int lvl_wait { get; set; }
        public short isactually { get; set; }
    
        public virtual DtoTAnnonce t_annonce { get; set; }
        public virtual DtoTCompetence t_competence { get; set; }
    }
}
