//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtoTGroup
    {
    
        public int id_group { get; set; }
        public int fk_id_user_admin { get; set; }
        public string group_nom { get; set; }
        public string group_description { get; set; }
        public System.DateTime group_create { get; set; }
    
        public virtual ICollection<DtoRefCompetenceGroup> ref_competence_group { get; set; }
        public virtual ICollection<DtoTMemberGroup> t_member_group { get; set; }
    }
}
