//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtoTLevel
    {
    
        public int id_level { get; set; }
        public double level_xp_up { get; set; }
        public string level_Rank { get; set; }
    
        public virtual ICollection<DtoTUserInfo> t_user_info { get; set; }
    }
}
