//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DtoTUser
    {
        public DtoTUser()
        {
           ref_competence_user = new List<DtoRefCompetenceUser>();
        }
        
        [DataMember]
        public int id_user { get; set; }
        [DataMember]
        public string user_nom { get; set; }
        [DataMember]
        public string user_prenom { get; set; }
        [DataMember]
        public string user_mail { get; set; }
        [DataMember]
        public string user_mdp { get; set; }
        [DataMember]
        public Nullable<System.DateTime> user_datenaissance { get; set; }
        [DataMember]
        public short user_isactif { get; set; }
        [DataMember]
        public string user_ip { get; set; }
        [DataMember]
        public System.DateTime user_create { get; set; }
        [DataMember]
        public System.DateTime user_modif { get; set; }
        [DataMember]
        public System.DateTime user_last_connexion { get; set; }
        [DataMember]    
        public virtual ICollection<DtoRefCompetenceUser> ref_competence_user { get; set; }
        [DataMember]
        public virtual ICollection<DtoRefUserAdress> ref_user_adress { get; set; }
        [DataMember]
        public virtual ICollection<DtoTAnnonce> t_annonce { get; set; }
        [DataMember]
        public virtual ICollection<DtoTAnnonce> t_annonce1 { get; set; }
        [DataMember]
        public virtual ICollection<DtoTAnnonceProposition> t_annonce_proposition { get; set; }
        [DataMember]
        public virtual ICollection<DtoRefTypeCarteBancaire> t_carte_bancaire { get; set; }
        [DataMember]
        public virtual ICollection<DtoTMemberGroup> t_member_group { get; set; }
        [DataMember]
        public virtual ICollection<DtoTRecompenseUser> t_recompense_user { get; set; }
        [DataMember]
        public virtual ICollection<DtoTUserInfo> t_user_info { get; set; }
        [DataMember]
        public virtual ICollection<DtoTRefFacturationHistorique> t_ref_facturation_historique { get; set; }

    }
}
