//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtoTDepartement
    {
    
        public int id_departement { get; set; }
        public Nullable<int> id_region { get; set; }
        public string departement_code { get; set; }
        public string departement_nom { get; set; }
        public string departement_nom_uppercase { get; set; }
        public string departement_slug { get; set; }
        public string departement_nom_soundex { get; set; }
    
        public virtual DtoTRegions t_regions { get; set; }
        public virtual ICollection<DtoTVilles> t_villes { get; set; }
    }
}
