//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;

    public partial class DtoTUserInfo
    {
        public int id_fk_user { get; set; }
        public int fk_id_typeuser { get; set; }
        public Nullable<int> fk_id_adresse { get; set; }
        public Nullable<int> fk_id_level { get; set; }
        public double userinfo_exp { get; set; }
        public byte[] userinfo_image { get; set; }
        public System.DateTime userinfo_date_modfif { get; set; }
    
        public virtual DtoRefUserAdress ref_user_adress { get; set; }
        public virtual DtoTLevel t_level { get; set; }
        public virtual DtoTTypeUser t_type_user { get; set; }
        public virtual DtoTUser t_user { get; set; }
    }
}
