//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtoTCategoryCompetence
    {
        public int id_category_comp { get; set; }
        public string category_comp_nom { get; set; }
    
        public virtual ICollection<DtoTCompetence> t_competence { get; set; }
    }
}
