//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;

    public partial class DtoTPins
    {
        public int id_pins { get; set; }
        public int fk_id_type_user { get; set; }
        public string pins_title { get; set; }
        public string pins_subtitle { get; set; }
        public string pins_description { get; set; }
    }
}
