//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DtoTStatutAnnonce
    {
    
        public int id_statutannonce { get; set; }
        public string statutannonce_nom { get; set; }
    
        public virtual ICollection<DtoTAnnonce> t_annonce { get; set; }
    }
}
