//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfAuctionJob.DataTransfertObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user
    {
        public t_user()
        {
            this.ref_competence_user = new HashSet<ref_competence_user>();
            this.ref_user_adress = new HashSet<ref_user_adress>();
            this.t_annonce = new HashSet<t_annonce>();
            this.t_annonce1 = new HashSet<t_annonce>();
            this.t_annonce_proposition = new HashSet<t_annonce_proposition>();
            this.t_carte_bancaire = new HashSet<t_carte_bancaire>();
            this.t_member_group = new HashSet<t_member_group>();
            this.t_recompense_user = new HashSet<t_recompense_user>();
            this.t_user_info = new HashSet<t_user_info>();
            this.t_ref_facturation_historique = new HashSet<t_ref_facturation_historique>();
        }
    
        public int id_user { get; set; }
        public string user_nom { get; set; }
        public string user_prenom { get; set; }
        public string user_mail { get; set; }
        public string user_mdp { get; set; }
        public Nullable<System.DateTime> user_datenaissance { get; set; }
        public short user_isactif { get; set; }
        public string user_ip { get; set; }
        public System.DateTime user_create { get; set; }
        public System.DateTime user_modif { get; set; }
        public System.DateTime user_last_connexion { get; set; }
    
        public virtual ICollection<ref_competence_user> ref_competence_user { get; set; }
        public virtual ICollection<ref_user_adress> ref_user_adress { get; set; }
        public virtual ICollection<t_annonce> t_annonce { get; set; }
        public virtual ICollection<t_annonce> t_annonce1 { get; set; }
        public virtual ICollection<t_annonce_proposition> t_annonce_proposition { get; set; }
        public virtual ICollection<t_carte_bancaire> t_carte_bancaire { get; set; }
        public virtual ICollection<t_member_group> t_member_group { get; set; }
        public virtual ICollection<t_recompense_user> t_recompense_user { get; set; }
        public virtual ICollection<t_user_info> t_user_info { get; set; }
        public virtual ICollection<t_ref_facturation_historique> t_ref_facturation_historique { get; set; }
    }
}
